moved image in repo, and created example in read me for setting up th…
aaemnnosttv/valet-dashboard pull request #6
Opened 2019-06-21 10:33 UTC by madsem

…e dashboard as default site.

2019-06-22 09:58 UTC, aaemnnosttv requested changes
A few minor changes to make and then this is good to go! 👍

2019-06-22 09:58 UTC, aaemnnosttv commented on README.md
> +you have to adjust the Valet config under `~/config/valet/config.json`.
* You have a typo in the path here: `config` should be `.config`
* Also, older installs may be using a different path to the config file, we should list both.

https://github.com/aaemnnosttv/valet-dashboard/blob/58a03f56b00f671348d50b42ee747a369f308be0/index.php#L2-L3

2019-06-22 09:58 UTC, aaemnnosttv commented on README.md
> +    "default": "/Users/yourname/yourpath/valet-dashboard",
Let's make this something a bit more generic since it could technically go anywhere. Something like `/path/to/valet-dashboard/` should be good 👍

2019-06-22 09:58 UTC, aaemnnosttv commented on README.md
> +        "/Users/yourname/yourpath"
Let's leave this array empty to emphasize the change.

2019-06-22 09:58 UTC, aaemnnosttv commented on README.md
> +    "domain": "dev",
Let's remove `domain` here since it's a legacy config value.

2019-06-23 08:45 UTC, aaemnnosttv commented
Made a few small wording changes and addressed the others. Thanks for your contribution!

2019-06-23 08:45 UTC, merged

2019-06-23 08:48 UTC, madsem commented
ah thanks :) Sorry, busy weekend for me. But I still have it on my list of things I want to do ;)